version: "3.1"

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    networks:
      - intent
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - intent
    depends_on:
      - mongodb

  exchange:
    image: harbor.intent.ai/interview/engineering
    container_name: intent-exchange
    environment:
      - BIDDER_ENDPOINT=http://api:${PORT}/bidding
    networks:
      - intent
    volumes:
      - ./:/app
networks:
  intent:
volumes:
  mongodb_data_container:
